FROM alpine:3.17

RUN apk update
RUN apk add --no-cache tini && \
    rm -f /var/cache/apk/*

ARG ARCH
ADD ./gotty/target/${ARCH}-unknown-linux-musl/release/gotty /usr/local/bin/gotty
RUN chmod +x /usr/local/bin/gotty
ADD ./docker_entrypoint.sh /usr/local/bin/docker_entrypoint.sh
RUN chmod a+x /usr/local/bin/docker_entrypoint.sh
