#!/bin/sh

curl -s -X POST -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"edgeencoder.GetStatus","params":[],"id":1}' http://localhost:18888/rpc | jq -r '.result | .address, .encoder_state, .status, .pending_tfuel'
