#!/bin/sh

echo "create_time,id,reward_tfuelwei" ; curl -s -X POST -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"edgeencoder.GetStatus","params":[],"id":1}' http://localhost:17935/rpc | jq -r '.result.recent_jobs[] | [.create_time, .id, .reward_tfuelwei] | @csv'
