# Theta EdgeStore multi-node privatenet configuration
p2p:
  port: 50000
  seeds: 70.251.209.207:50000,141.193.65.7:50000
#  seeds: 70.251.209.207:50000
  bootstrapSeeds: 127.0.0.1:16888
  minNumPeers: 1
  maxNumPeers: 96
  maxInitiallyAttemptedPeers: 64
  maxConnections: 2048
  connectionFIFO: true
  #natMapping: true
storage:
  shardPriorityThreshold: 500000
rpc:
  port: 19888
  enabled: true
  address: 127.0.0.1
rest:
  port: 8080
  enabled: true
  address: 0.0.0.0
log:
  levels: "*:info"